### ISSUE TITLE
LPPL 1.3c 授权兼容问题

### ISSUE THREAD

**Issue by RuixiZhang42** [YangLaTeX/hitszthesis#1]
MTPro II Lite Fonts End User License Agreement 跟 MTPro II Fonts End User License Agreement 两款授权条款都和 The LaTeX Project Public License 1.3c 直接冲突。

请考虑将 wiki 超链接指向官方授权网站 https://www.pctex.com/mtpro2.html 避免论文用户收律师函。

Times New Roman 风格的免费（而且正版）的数学字体除了 `newtxmath` 之外还有很多，例如：
- [STIX](https://github.com/stipub/stixfonts)，CTAN 收了，有 Type1 格式，支持 PDFLaTeX 编译；
- [XITS](https://github.com/alif-type/xits)，CTAN 收了，只有 OpenType 格式，需要通过 `unicode-math` 宏包使用；
- [TeX Gyre Termes Math](http://www.gust.org.pl/projects/e-foundry/tg-math)，CTAN 收了，只有 OpenType 格式，需要通过 `unicode-math` 宏包使用。

最后，请更改用户文档，说明「字体需要购买授权」而不是提示用户去「下载」。

参考：https://zhuanlan.zhihu.com/p/109030716

**Comment by YangLaTeX** [comment]
感谢提醒，我尽快及全部更改

**Comment by YangLaTeX** [comment]
感谢提醒，已更改
