### ISSUE TITLE
最后的参考文献列表，方括号字体的问题

### ISSUE THREAD

**Issue by MetaT1an** [YangLaTeX/hitszthesis#4]
根据最新的深圳校区规范，最后的参考文献列表标号，方括号的字体由**新罗马**变成了**宋体**，请问这个要在哪里进行修改？
![image](https://user-images.githubusercontent.com/33452141/140605036-0df68c76-c505-40e8-b141-19b0b703200d.png)

**Comment by YangLaTeX** [comment]
Hello, the format of reference is modified according to the new regulations. Please kindly use version 3.2.1 of this template.
