### ISSUE TITLE
本科前言部分页码问题

### ISSUE THREAD

**Issue by Deadpoolmine** [YangLaTeX/hitszthesis#6]
学长你好，本科毕设要求前言部分（正文前）仅用罗马数字编排，示例中没有前后两个横杠：“- X -”，请问如何调整模板以达到：“X”这种效果呢？（如下图所示）
![image](https://user-images.githubusercontent.com/48178553/171164024-2c53b25b-e3bd-425c-9368-c9a1396d74d2.png)

**Comment by YangLaTeX** [comment]
可以设置 `bsfrontpagenumberline=false`
