### ISSUE TITLE
硕士学位论文页眉问题

### ISSUE THREAD

**Issue by libwo** [YangLaTeX/hitszthesis#7]
学长你好，21年硕士研究生学位论文规定：除摘要、目录的页眉对应本页标题字样以外，从绪论开始，页眉均为“哈尔滨工业大学□学硕士学位论文”。
在Tex硕士论文模板中，摘要、目录的页眉对应的页眉也为 哈尔滨工业大学□学硕士学位论文
![image](https://user-images.githubusercontent.com/64256867/177933836-87c057c9-8172-45e1-a60e-26c1cfa3ab7c.png)
请问应该如何修改呢

**Comment by libwo** [comment]
对比hithesis，修改以下部分即可  
```
 \ifhitsz@shenzhen
        \if@mainmatter%
          \fancyhead[C]{\songti\xiaowu[0]\hitsz@cschoolname\hitsz@cdegree\hitsz@cthesisname}
        \else%
          \fancyhead[C]{\songti\xiaowu[0]\leftmark}%
        \fi
      \fi
```
![image](https://user-images.githubusercontent.com/64256867/178665894-c2a2115c-60ca-4f09-a17d-6e06265d3147.png)

**Comment by YangLaTeX** [comment]
已修改，感谢提醒
